import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-gray-100`}
      >
          <nav className="bg-white p-4 shadow-md flex justify-between sticky top-2 z-20">
            <Link href="/"><h1 className="text-xl font-bold text-gray-800">SERVICOM NYSC</h1></Link>
            <div className="flex gap-2">
              <Link href="/complaint" className="text-blue-500">Submit Complaint</Link>
              <Link href="/status" className="text-blue-500">Check Status</Link>
              {/* <Link href="/login" className="text-blue-500">Login</Link> */}
            </div>
          </nav>
          {children}
      </body>
    </html>
  );
}
